services:
  - type: web
    name: ecom
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y gcc python3-dev  # Install system dependencies
      pip install -r requirements.txt  # Then install Python packages
    startCommand: gunicorn ecom.wsgi --log-file -
    pythonVersion: 3.9
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ${DATABASE_NAME}
          property: connectionString
      - key: SECRET_KEY
        value: ${SECRET_KEY}
databases:
  - name: ${DATABASE_NAME}
    plan: free
