# Generated by Django 4.2.13 on 2024-05-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_prix_product_price_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
