# Generated by Django 4.2.13 on 2024-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_complate_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
